### ISSUE TITLE
Invalid codepath for cpp_map(UPDATE)

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [CMakePP/CMakePPLang#124]
**Describe the bug**
Calling `cpp_map(UPDATE)` results in a call to `cpp_map_update()`, which is not a function. The correct function appears to be `cpp_map_merge()`, in which case the top-level subcommand should be renamed to match.

See:
https://github.com/CMakePP/CMakePPLang/blob/ea8a0212581757077edb29f864662c632f0fedcb/cmake/cmakepp_lang/map/map.cmake#L82-L83

Introduced by #22. Tests only test the discrete `cpp_map_merge()` function and do not test that the top-level command delegates to it correctly.
